pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-2'
        S3_BUCKET = 'office-records-frontend'
        CLOUDFRONT_DIST = 'E252RQP7IK1CVC'
        LAMBDA_FUNCTION = 'office-records-api'
        API_ID = 'h4uoooso2l'
        STAGE = 'prod'
    }

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/sanjaiparanitharan/office-contact-manager.git'
            }
        }

        stage('Clone Repo') {
    steps {
        git branch: 'main', url: 'https://github.com/sanjaiparanitharan/office-contact-manager.git'
    }
}

        stage('Invalidate CloudFront Cache') {
            steps {
                sh 'aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST --paths "/*"'
            }
        }

        stage('Deploy Lambda Backend') {
            steps {
                sh '''
                cd office-records-app/backend
                zip -r lambda.zip .
                aws lambda update-function-code \
                  --function-name $LAMBDA_FUNCTION \
                  --zip-file fileb://lambda.zip \
                  --region $AWS_REGION
                '''
            }
        }

        stage('Deploy API Gateway') {
            steps {
                sh '''
                aws apigateway create-deployment \
                  --rest-api-id $API_ID \
                  --stage-name $STAGE \
                  --region $AWS_REGION
                '''
            }
        }
    }

    post {
        success { echo "✅ Deployment Successful" }
        failure { echo "❌ Deployment Failed" }
    }
}



